import pygame

# Screen dimensions
SCREEN_WIDTH = 1200
SCREEN_HEIGHT = 800

# Colors
BLACK = (0, 0, 0)
WHITE = (255, 255, 255)
RED = (255, 0, 0)
GREEN = (0, 255, 0)
BLUE = (0, 0, 255)
YELLOW = (255, 255, 0)
CYAN = (0, 255, 255)
MAGENTA = (255, 0, 255)
ORANGE = (255, 165, 0)
PURPLE = (128, 0, 128)
GRAY = (128, 128, 128)
DARK_GRAY = (64, 64, 64)
LIGHT_GRAY = (192, 192, 192)

# Game settings
FPS = 60
GRAVITY = 0.5
MAX_FALL_SPEED = 10

# Player settings
PLAYER_SPEED = 5
PLAYER_JUMP_STRENGTH = 12
PLAYER_WIDTH = 40
PLAYER_HEIGHT = 60
PLAYER_HEALTH = 100
PLAYER_MAX_HEALTH = 100

# Enemy settings
ENEMY_SPEED = 2
ENEMY_WIDTH = 40
ENEMY_HEIGHT = 60
ENEMY_HEALTH = 50
ENEMY_DAMAGE = 10

# Projectile settings
PROJECTILE_SPEED = 10
PROJECTILE_WIDTH = 10
PROJECTILE_HEIGHT = 10
PROJECTILE_DAMAGE = 25

# Power-up settings
POWERUP_WIDTH = 30
POWERUP_HEIGHT = 30
HEALTH_RESTORE = 25
SHIELD_DURATION = 5000  # milliseconds
SPEED_BOOST_DURATION = 5000
SPEED_BOOST_MULTIPLIER = 1.5

# Platform settings
PLATFORM_WIDTH = 100
PLATFORM_HEIGHT = 20

# UI settings
FONT_SIZE = 24
SMALL_FONT_SIZE = 18
LARGE_FONT_SIZE = 36

# Game states
STATE_MENU = "menu"
STATE_PLAYING = "playing"
STATE_PAUSED = "paused"
STATE_GAME_OVER = "game_over"
STATE_VICTORY = "victory"

# Input keys
KEY_LEFT = pygame.K_LEFT
KEY_RIGHT = pygame.K_RIGHT
KEY_UP = pygame.K_UP
KEY_DOWN = pygame.K_DOWN
KEY_JUMP = pygame.K_SPACE
KEY_SHOOT = pygame.K_LCTRL
KEY_PAUSE = pygame.K_ESCAPE
KEY_RESTART = pygame.K_r

# Sound settings
MUSIC_VOLUME = 0.5
SFX_VOLUME = 0.7

# Level settings
LEVEL_WIDTH = 2400
LEVEL_HEIGHT = 800
TILE_SIZE = 40

# Animation settings
ANIMATION_SPEED = 100  # milliseconds per frame

# Particle settings
PARTICLE_LIFETIME = 1000  # milliseconds
PARTICLE_COUNT = 20

# Camera settings
CAMERA_SMOOTHNESS = 0.1
CAMERA_DEADZONE_WIDTH = 200
CAMERA_DEADZONE_HEIGHT = 150

# Difficulty settings
EASY_ENEMY_MULTIPLIER = 0.7
NORMAL_ENEMY_MULTIPLIER = 1.0
HARD_ENEMY_MULTIPLIER = 1.5

# Achievement settings
ACHIEVEMENT_UNLOCK_TIME = 3000  # milliseconds to show

# Save settings
SAVE_FILE = "savegame.json"
CONFIG_FILE = "config.json"

# Debug settings
DEBUG_MODE = False
SHOW_HITBOXES = False
SHOW_FPS = True

# Networking settings
DEFAULT_PORT = 5555
MAX_PLAYERS = 4
NETWORK_TIMEOUT = 5000  # milliseconds

# Ship types
SHIP_JAGUAR = "jaguar"
SHIP_PUNISHER = "punisher"
SHIP_RIFTER = "rifter"

# Ship-specific bonuses
JAGUAR_SPEED_BONUS = 1.2
JAGUAR_DAMAGE_BONUS = 1.1
FORMATION_SWITCH_KEY = pygame.K_f
PUNISHER_ARMOR_BONUS = 1.3
PUNISHER_SPEED_PENALTY = 0.9
RIFTER_SPEED_BONUS = 1.15
RIFTER_SHIELD_BONUS = 1.1

# Formation types
FORMATION_LINE = "line"
FORMATION_V = "v_formation"
FORMATION_WEDGE = "wedge"
FORMATION_DIAMOND = "diamond"

# Formation spacing
FORMATION_SPACING = 100
FORMATION_OFFSET_Y = 80

# AI settings
AI_REACTION_TIME = 500  # milliseconds
AI_AGGRESSION_RANGE = 300
AI_FLEE_HEALTH_THRESHOLD = 0.3

# Economy settings
STARTING_CREDITS = 1000
MISSION_REWARD_MULTIPLIER = 1.5
BOUNTY_MULTIPLIER = 2.0
