name: Feature Request
description: Suggest a new feature or improvement
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Have an idea to improve the game? We'd love to hear it!

  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: What would you like to see added or changed?
      placeholder: Describe the feature...
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Category
      options:
        - Gameplay
        - New Content (enemies, stages, ships)
        - UI/UX
        - Controls
        - Audio
        - Performance
        - Other
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Why would this feature be useful?
      placeholder: This would help players...
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions?
    validations:
      required: false
